# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
sudo: required

services:
- docker

language: python

python:
- 3.5

before_install:
- docker pull ubuntu:bionic

script:
# Build wp-base first (because other images depend on it)
- |
  set -e -x
  docker build -t epflidevelop/os-wp-base docker/wp-base
  find docker -mindepth 1 -maxdepth 1 -type d | xargs -t docker build
