# Collect WordPress-specific Ansible facts

- name: Inspect WordPress installed files
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ wp_path_config_php }}"
    - "{{ wp_path_wpadmin }}"
  register: _wp_stat

- name: Inspect WordPress plug-ins
  shell: wp --path="{{ wp_dir }}" plugin list --format=json
  register: _wp_plugin_list_json
  changed_when: false
  failed_when: false

- set_fact:
    wp_is_installed: "{{ _wp_stat.results[0].stat.exists }}"
    wp_is_symlinked: "{{ _wp_stat.results[1].stat.islnk }}"
    wp_plugin_list: >-
      {{ (_wp_plugin_list_json.stdout if _wp_plugin_list_json.rc == 0
                                      else '[]')
         | from_json }}

- tags: ["never", "_debug_facts"]
  debug:
    msg:
      - "{{ wp_is_installed }}"
      - "{{ wp_is_symlinked }}"
      - "{{ wp_plugin_list }}"
