# file: roles/wordpress-instance/tasks/main.yml
#
# What to do to install and configure a WordPress instance
#
# Variables:: (in addition to those defined or documented in
#              ../vars/*.yml)

- include_vars: wp-destructive.yml
  tags: always

- name: "Backup"
  import_tasks: "backup.yml"
  tags:
    - never  # That is, skip unless "-t backup" or "-t wipe" is
             # passed on the command line
    - wipe
    - backup

- name: "Wipe"
  import_tasks: "wipe.yml"
  tags:
    - never
    - wipe

- name: Check whether WordPress is already installed
  stat:
    path: "{{ wp_path_config_php }}"
  register: _wp_config_php_stat

- name: "{{ 'Recreate' if 'wipe' in ansible_run_tags else 'Create' }}"
  include_tasks: "create.yml"
  when: not _wp_config_php_stat.stat.exists

- name: Restore
  import_tasks: "restore.yml"
  tags:
    - never
    - restore

- name: Check that WordPress is working
  command: "{{ wp_cli_command }} eval '1;'"
  changed_when: false

- name: Configure
  when: wp_can.any
  tags: config
  include_tasks:
    file: "configure.yml"
    # Because `include_tasks` is dynamic, tags don't auto-inherit.
    apply:
      tags: ["config"]

#################################################################
# Special-purpose tasks
#################################################################

# These tasks are used in "ventilation" (site move) workflows only
- name: "Dump WXR"
  import_tasks: "dump.yml"
  tags:
    - never
    - dump
- name: "Undump WXR"
  import_tasks: "undump.yml"
  tags:
    - never
    - undump
