# file: roles/wordpress-instance/tasks/main.yml
#
# What to do to install and configure a WordPress instance
#
# Variables:: (in addition to those defined or documented in
#              ../vars/*.yml)

- include_vars: wp-destructive.yml
  tags: always

- name: WordPress facts
  import_tasks: facts.yml
  tags: always

- name: Backup
  import_tasks: "backup.yml"
  tags:
    - never  # That is, skip unless "-t backup" or "-t wipe" is
             # passed on the command line
    - wipe
    - backup

- name: Wipe
  import_tasks: "wipe.yml"
  tags:
    - never
    - wipe

- name: "{{ 'Recreate' if 'wipe' in ansible_run_tags else 'Create' }}"
  include_tasks: "create.yml"
  when: "'wipe' in ansible_run_tags or not wp_is_installed"

- name: Restore
  import_tasks: "restore.yml"
  tags:
    - never
    - restore

- name: Check that WordPress is working
  command: "{{ wp_cli_command }} eval '1;'"
  changed_when: false

- name: "Set up / revert “symlink” serving discipline"
  when: wp_can.configure or ansible_check_mode
  tags:
    - never
    - symlink
    - unsymlink
  # We include_tasks (not import_tasks) here, because we do *not* want
  # to propagate tags - Within symlink.yml, tasks shall be
  # individually marked with either (or both) the `symlink` and
  # `unsymlink` tags (or alternatively, the `always` tag).
  include_tasks: "symlink.yml"

- name: Configure
  when: wp_can.configure
  tags:
    - config
  include_tasks:    # Required because of the "when" clause
    file: "configure.yml"
    # Because `include_tasks` is dynamic, tags don't auto-inherit.
    apply:
      tags: ["config"]

################################
# Special-purpose tasks
################################

# "Ventilation"-related
- name: "Dump to WXR for ventilation"
  import_tasks: "dump.yml"
  tags:
    - never
    - dump
- name: "Undump from WXR for ventilation"
  import_tasks: "undump.yml"
  tags:
    - never
    - undump

- name: CSV inventory report
  tags:
    - never
    - reportcsv
  local_action:
    module: copy
    dest: "./report.csv"
    content: '{{ hostvars | wp_inventory_csv_report }}'
