# Restore a WordPress site from backup

- include_vars: wp-destructive.yml

- assert:
    that:
      - inventory_hostname in wp_destructive
      - wp_can.write_data
      - wp_restore_from is defined

- import_tasks: restore-over-ssh.yml

# TODO: There should be a choice to restore from other sources, such as
# local tarball, possibly in sti-test.epfl.ch format

