# Ansible pre-configuration and fact gathering 

- name: Ansible pre-configuration
  set_fact:
    ansible_user: www-data
    ansible_python_interpreter: "/srv/{{wp_env}}/venv/bin/python"

- name: Gathering facts (delayed after Ansible pre-configuration)
  setup:

- name: Examine WordPress install
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ wp_path_config_php }}"
    - "{{ wp_path_wpadmin }}"
  register: _wp_stat

- set_fact:
    wp_is_installed: "{{ _wp_stat.results[0].stat.exists }}"
    wp_is_symlinked: "{{ _wp_stat.results[1].stat.islnk }}"
