- include_vars: wp-destructive.yml   # For wp_can
- assert:
    that: wp_can.configure

- name: Delete themes bundled with WordPress
  wordpress_theme:
    name: "{{ item }}"
    state: absent
  with_items:
    - twentyfifteen
    - twentysixteen
    - twentyseventeen
