# Delete a WordPress site

- include_vars: wp-destructive.yml
- include_vars: jahia2wp-vars.yml

- assert:
    that:
      - wp_can.wipe

- name: jahia2wp.py clean
  shell: "{{ jahia2wp_shell }} clean {{ wp_env }} {{ jahia2wp_url }}"
  environment: "{{ jahia2wp_env }}"
