# Ansible playbook for the EPFL WordPress stack

- name: Initial checks
  hosts: all
  gather_facts: no    # Ansible facts are useless for this play
  tasks:
    - name: Check Ansible version
      run_once: true
      assert:
        that: "ansible_version.full is version_compare('2.6', '>=')"
        msg: |
          You must update Ansible to at least 2.6 to use this playbook.

# In this play, "hosts" are not really hosts; rather, they are
# WordPress instances. See the list in
# ../inventory/test/wordpress-instances (a plain file) and
# ../inventory/prod/wordpress-instances (an executable script, that lists
# them on standard output)
- name: WordPress instances
  hosts: all-wordpresses
  gather_facts: no   # But see ../roles/wordpress-instance/tasks/facts.yml

  # Set execution strategy to "free" (full parallelism) under -t
  # symlink / -t unsymlink to minimize downtime; and to "linear" (the
  # default value, slower but easier to reason about) otherwise
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html
  strategy: >-
    {{ "free" if ["symlink", "unsymlink"] | intersect(ansible_run_tags)
       else "linear" }}
  roles:
    - role: ../roles/wordpress-instance

# Likewise, members of all-openshift-namespaces are OpenShift
# namespaces, not hosts
- name: OpenShift namespaces
  hosts: all-openshift-namespaces
  gather_facts: no    # Ansible facts are useless for this play
  roles:
    - role: ../roles/wordpress-openshift-namespace
