---
# tasks for WordPress OpenShift namespaces

- name: "Disk usage report microservice"
  include: disk-usage-report.yml
  tags: diskusage

- name: "Images and builds"
  include: images.yml
  tags: images

- name: "DeploymentConfigs (previously known as pods)"
  include_tasks:
    file: deploymentconfig-httpd.yml
    apply:
      tags: ["dc"] # Tags don't seem to work the same way within /
                   # without a loop, #smellslikeabug
  loop: "{{ DeploymentConfigs.httpd }}"
  loop_control:
    loop_var: dc
  tags: dc

- name: "Continuous integration"
  when: openshift_namespace == "wwp-test"
  include_tasks:
    file: continuous-integration.yml
    apply:
      tags:
        - ci
  # Multi-level tagging: `-t ci` will run all of continuous-integration.yml,
  # while `-t ci.jenkinsfile` will only load the BuildConfig with the
  # Jenkinsfile inside
  tags:
    - ci
    - ci.jenkinsfile

- name: "Management container (ssh server, PHP CLI)"
  include: mgmt.yml
  tags: mgmt

- name: "Monitoring"
  when: openshift_namespace == "wwp"
  include: monitoring.yml
  tags: monitoring
