- name: "Create or update `{{ awx_wpveritas_inventory_script_name }}` custom inventory script"
  awx_script:
    script: |
      from awx.main.models.inventory import CustomInventoryScript

      exit_json(changed=False)
    vars:
      wpveritas_inventory_script: '{{ lookup("file", awx_wpveritas_inventory_script_path) }}'
